/// Regenerates the Material Icons tables from the Flutter SDK.
///
///   dart tool/generate_material_icons.dart [path/to/flutter]
///
/// Flutter's own `Icons` class is the source of truth: it carries the
/// codepoints of the `MaterialIcons-Regular.otf` font that
/// `uses-material-design: true` bundles into every build, which is the font
/// the native renderers draw from. Taking the numbers from anywhere else would
/// be guessing at what is in that file.
///
/// Every name is taken into `Icons`, the outlined, rounded and sharp ones
/// included: Flutter declares all of them in the one `MaterialIcons` family,
/// so they are glyphs of that same file. A declaration in any other family
/// stops the run, since no renderer here would have the font for it.
///
/// The name table (`materialIconCodepoint`) keeps the base names only. It is
/// a map looked up at run time, so unlike the `Icons` constants none of it
/// tree-shakes, and the variants would make it four times the size in every
/// web build. A variant is reached as `Icons.home_outlined.codePoint`.
///
/// The web shell gets the same font file, so a codepoint draws the same
/// picture in a browser: it is rewrapped as WOFF2 (the tables compressed,
/// nothing altered) into `web_shell/vendor/material-icons/`, with its licence.
/// That step needs the `brotli` command.
library;

import 'dart:io';
import 'dart:typed_data';

void main(List<String> args) {
  final flutterRoot = args.isNotEmpty ? args.first : _flutterRootFromPath();
  final source = File(
    '$flutterRoot/packages/flutter/lib/src/material/icons.dart',
  );
  if (!source.existsSync()) {
    stderr.writeln('No icons.dart under $flutterRoot - pass the SDK path.');
    exit(2);
  }

  final pattern = RegExp(
    r"^  static const IconData (\w+) = IconData\(\s*(0x[0-9a-fA-F]+),"
    r"\s*fontFamily: 'MaterialIcons'",
    multiLine: true,
  );
  final text = source.readAsStringSync();
  final icons = <String, String>{};
  for (final match in pattern.allMatches(text)) {
    icons[match.group(1)!] = match.group(2)!;
  }
  final declared = RegExp(
    r'^  static const IconData \w+ = ',
    multiLine: true,
  ).allMatches(text).length;
  if (declared != icons.length) {
    stderr.writeln(
      '$declared icons declared, ${icons.length} in MaterialIcons - '
      'the rest are in a font nothing here draws from.',
    );
    exit(2);
  }
  final names = icons.keys.toList()..sort();
  final baseNames = [
    for (final name in names)
      if (!_variant.hasMatch(name)) name,
  ];
  stdout.writeln(
    '${names.length} icons (${baseNames.length} base names) from $flutterRoot',
  );

  _writeCodepoints(baseNames, icons);
  _writeIcons(names, icons);
  _writeWebFont(flutterRoot);
}

/// The styles Flutter draws beside the filled one, by the suffix it names
/// them with.
final _variant = RegExp(r'_(outlined|rounded|sharp)$');

String _flutterRootFromPath() {
  final flutter = Process.runSync('which', ['flutter']).stdout as String;
  final bin = File(flutter.trim()).resolveSymbolicLinksSync();
  return Directory(bin).parent.parent.path;
}

void _writeCodepoints(List<String> names, Map<String, String> icons) {
  final buffer = StringBuffer('''
/// Material Icons codepoints, so the native renderers can draw a glyph from the
/// `MaterialIcons-Regular.otf` font Flutter already bundles (via
/// `uses-material-design: true`) rather than an approximate system drawable.
///
/// The values are the codepoints from Flutter's own `Icons` class, so an icon
/// drawn here matches the one a Flutter-hosted screen would draw - on the web
/// too, whose shell ships the same font. A builder that is given a name sends
/// it and, when it is a known one, the codepoint.
///
/// Base names only: the outlined, rounded and sharp variants are in `Icons`,
/// where an unused one costs nothing, and not in this map, which is kept
/// whole by any build that looks a name up.
///
/// Pure Dart on purpose: this file is reachable from the web build, which has no
/// Flutter engine, so it cannot import `package:flutter`.
///
/// GENERATED by `tool/generate_material_icons.dart`; do not edit by hand.
library;

/// Codepoint for a Material Icons [name], or null if it is not in the table.
/// A caller that needs an icon not listed here can pass its codepoint directly.
int? materialIconCodepoint(String name) => _codepoints[name];

/// How many icons the table knows, for the test that guards the generation.
int get materialIconCount => _codepoints.length;

const Map<String, int> _codepoints = {
''');
  for (final name in names) {
    buffer.writeln("  '$name': ${icons[name]},");
  }
  buffer.writeln('};');
  File(
    'packages/native_bridge/lib/src/material_icons.dart',
  ).writeAsStringSync(buffer.toString());
}

void _writeIcons(List<String> names, Map<String, String> icons) {
  final buffer = StringBuffer('''
/// The Material icons an app can name, with Flutter's own names and
/// codepoints - so `Icons.search` means the same glyph here and there. All of
/// Flutter's are here, `_outlined`, `_rounded` and `_sharp` included: they are
/// glyphs of the same font, and a constant nothing uses is not compiled in.
///
/// GENERATED by `tool/generate_material_icons.dart`; do not edit by hand.
// The names are Flutter's, underscores and all.
// ignore_for_file: constant_identifier_names
library;

import 'icon_data.dart';

abstract final class Icons {
''');
  // Flutter's names as they stand: it has already spelled the ones that
  // would not be identifiers (`class_`, `eight_k`), and `extension` is one.
  for (final name in names) {
    buffer.writeln(
      "  static const IconData $name = IconData(${icons[name]}, name: '$name');",
    );
  }
  buffer.writeln('}');
  File(
    'packages/native_bridge/lib/src/icons.dart',
  ).writeAsStringSync(buffer.toString());
}

/// The tags WOFF2 gives a number to, in the order it numbers them; any other
/// table is written with its tag in full.
const _knownTags = [
  'cmap', 'head', 'hhea', 'hmtx', 'maxp', 'name', 'OS/2', 'post', 'cvt ',
  'fpgm', 'glyf', 'loca', 'prep', 'CFF ', 'VORG', 'EBDT', 'EBLC', 'gasp',
  'hdmx', 'kern', 'LTSH', 'PCLT', 'VDMX', 'vhea', 'vmtx', 'BASE', 'GDEF',
  'GPOS', 'GSUB', 'EBSC', 'JSTF', 'MATH', 'CBDT', 'CBLC', 'COLR', 'CPAL',
  'SVG ', 'sbix', 'acnt', 'avar', 'bdat', 'bloc', 'bsln', 'cvar', 'fdsc',
  'feat', 'fmtx', 'fvar', 'gvar', 'hsty', 'just', 'lcar', 'mort', 'morx',
  'opbd', 'prop', 'trak', 'Zapf', 'Silf', 'Glat', 'Gloc', 'Feat', 'Sill', //
];

/// [value] as WOFF2 writes a length: seven bits to a byte, most significant
/// first, the top bit set on every byte but the last.
List<int> _base128(int value) {
  final bytes = [value & 0x7f];
  for (var rest = value >> 7; rest > 0; rest >>= 7) {
    bytes.insert(0, (rest & 0x7f) | 0x80);
  }
  return bytes;
}

/// Puts Flutter's icon font where the web shell serves it from, as WOFF2.
///
/// WOFF2 is the same tables end to end in one Brotli stream, behind a
/// directory that says how big each was: about a quarter of the font's size
/// on the wire, three quarters of what WOFF made of it, and nothing a browser
/// cannot undo exactly. The tables are stored as they are - the transforms
/// WOFF2 offers are for TrueType outlines, and these are CFF.
///
/// Brotli is not in the Dart SDK, so this runs the `brotli` command
/// (`brew install brotli`, `apt install brotli`). Only this tool needs it.
void _writeWebFont(String flutterRoot) {
  const fonts = 'bin/cache/artifacts/material_fonts';
  const vendor = 'packages/native_bridge/web_shell/vendor/material-icons';
  final otf = File('$flutterRoot/$fonts/MaterialIcons-Regular.otf');
  if (!otf.existsSync()) {
    stderr.writeln('No ${otf.path} - run `flutter precache` first.');
    exit(2);
  }
  final sfnt = otf.readAsBytesSync();
  final header = ByteData.sublistView(sfnt);
  final count = header.getUint16(4);

  // An sfnt directory entry is tag, checksum, offset, length.
  final tables = [
    for (var i = 0; i < count; i++)
      (
        tag: String.fromCharCodes(sfnt, 12 + 16 * i, 16 + 16 * i),
        offset: header.getUint32(20 + 16 * i),
        length: header.getUint32(24 + 16 * i),
      ),
  ];
  for (final table in tables) {
    // Stored untransformed, which for these two WOFF2 has to be told.
    if (table.tag == 'glyf' || table.tag == 'loca') {
      stderr.writeln('${otf.path} has TrueType outlines; this writes CFF.');
      exit(2);
    }
  }
  int padded(int length) => (length + 3) & ~3;

  final directory = BytesBuilder();
  final body = BytesBuilder();
  var sfntSize = 12 + 16 * count;
  for (final table in tables) {
    final known = _knownTags.indexOf(table.tag);
    directory
      ..addByte(known < 0 ? 63 : known)
      ..add(known < 0 ? table.tag.codeUnits : const [])
      ..add(_base128(table.length));
    body.add(
      Uint8List.sublistView(sfnt, table.offset, table.offset + table.length),
    );
    sfntSize += padded(table.length);
  }

  final scratch = Directory.systemTemp.createTempSync('material_icons');
  final List<int> compressed;
  try {
    final plain = File('${scratch.path}/tables')
      ..writeAsBytesSync(body.takeBytes());
    final packed = File('${scratch.path}/tables.br');
    final ProcessResult brotli;
    try {
      brotli = Process.runSync('brotli', [
        '--quality=11',
        '--lgwin=24',
        '--output=${packed.path}',
        plain.path,
      ]);
    } on ProcessException {
      stderr.writeln('No `brotli` command - install it to write the web font.');
      exit(2);
    }
    if (brotli.exitCode != 0) {
      stderr.writeln('brotli failed: ${brotli.stderr}');
      exit(2);
    }
    compressed = packed.readAsBytesSync();
  } finally {
    scratch.deleteSync(recursive: true);
  }

  final entries = directory.takeBytes();
  final length = padded(48 + entries.length + compressed.length);
  final woff2 = ByteData(48)
    ..setUint32(0, 0x774F4632) // 'wOF2'
    ..setUint32(4, header.getUint32(0)) // the flavour: 'OTTO', CFF outlines
    ..setUint32(8, length)
    ..setUint16(12, count)
    ..setUint32(16, sfntSize)
    ..setUint32(20, compressed.length);
  final out = File('$vendor/MaterialIcons-Regular.woff2')
    ..writeAsBytesSync([
      ...woff2.buffer.asUint8List(),
      ...entries,
      ...compressed,
      ...Uint8List(length - 48 - entries.length - compressed.length),
    ]);
  File(
    '$flutterRoot/$fonts/MaterialIcons_LICENSE.txt',
  ).copySync('$vendor/LICENSE');
  stdout.writeln(
    '${out.path}: ${sfnt.length} bytes of font in ${out.lengthSync()}',
  );
}
