/// Regenerates the table of how each locale writes a time of day.
///
///   dart tool/generate_time_formats.dart [path/to/flutter]
///
/// Flutter's own localizations are the source: `flutter_localizations` keeps,
/// for every locale it supports, the pattern a time is written in
/// (`timeOfDayFormat`) and the two words for the halves of the day. Those
/// are what `TimeOfDay.format` answers with in a Flutter app, so taking them
/// from there is what makes `TimeOfDay.format` here answer the same.
///
/// A regional locale is written only where it differs from its language:
/// `en_GB` is there because Britain writes `HH:mm` and English `h:mm a`;
/// `en_CA` is not, because it writes what English does.
library;

import 'dart:convert';
import 'dart:io';

/// The six ways Flutter knows to write a time (`TimeOfDayFormat`), by the
/// spellings its data uses for them.
const _patterns = {
  'H:mm': 'H:mm',
  'HH:mm': 'HH:mm',
  'HH.mm': 'HH.mm',
  'h:mm a': 'h:mm a',
  'a h:mm': 'a h:mm',
  // No space in the data, and none in what Flutter then writes either way:
  // its generator reads both as the one format.
  'ah:mm': 'a h:mm',
  "HH 'h' mm": "HH 'h' mm",
};

void main(List<String> args) {
  final flutterRoot = args.isNotEmpty ? args.first : _flutterRootFromPath();
  final l10n = Directory(
    '$flutterRoot/packages/flutter_localizations/lib/src/l10n',
  );
  if (!l10n.existsSync()) {
    stderr.writeln('No ${l10n.path} - pass the SDK path.');
    exit(2);
  }

  // What each file says for itself, by locale tag (`en`, `en_GB`).
  final stated = <String, Map<String, String>>{};
  for (final file in l10n.listSync().whereType<File>()) {
    final name = file.uri.pathSegments.last;
    final match = RegExp(r'^material_(\w+)\.arb$').firstMatch(name);
    if (match == null) continue;
    final arb = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    stated[match.group(1)!] = {
      for (final key in const [
        'timeOfDayFormat',
        'anteMeridiemAbbreviation',
        'postMeridiemAbbreviation',
      ])
        if (arb[key] is String) key: arb[key] as String,
    };
  }

  /// [tag]'s value for [key]: its own, or its language's.
  String? resolve(String tag, String key) {
    var at = tag;
    while (true) {
      final value = stated[at]?[key];
      if (value != null) return value;
      final cut = at.lastIndexOf('_');
      if (cut < 0) return null;
      at = at.substring(0, cut);
    }
  }

  final table = <String, (String, String, String)>{};
  for (final tag in stated.keys.toList()..sort()) {
    final raw = resolve(tag, 'timeOfDayFormat');
    final pattern = _patterns[raw];
    if (pattern == null) {
      stderr.writeln('$tag writes a time as "$raw", which is not known here.');
      exit(2);
    }
    final entry = (
      pattern,
      resolve(tag, 'anteMeridiemAbbreviation') ?? 'AM',
      resolve(tag, 'postMeridiemAbbreviation') ?? 'PM',
    );
    final cut = tag.lastIndexOf('_');
    // A region that writes what its language does needs no line of its own:
    // the lookup falls back to the language.
    if (cut > 0 && table[tag.substring(0, cut)] == entry) continue;
    table[tag] = entry;
  }
  // `zh_TW` is asked for as often as `zh_Hant_TW`: the same answer under the
  // shorter tag, where the shorter tag is not already something else.
  for (final tag in table.keys.toList()) {
    final parts = tag.split('_');
    if (parts.length != 3) continue;
    table.putIfAbsent('${parts[0]}_${parts[2]}', () => table[tag]!);
  }

  String quoted(String text) =>
      "'${text.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'";

  final out = StringBuffer('''
/// GENERATED by tool/generate_time_formats.dart - do not edit by hand.
///
/// How each locale writes a time of day: the pattern, and its words for the
/// two halves of the day. Taken from the Flutter SDK's `flutter_localizations`
/// (its `timeOfDayFormat`, `anteMeridiemAbbreviation` and
/// `postMeridiemAbbreviation`), so `TimeOfDay.format` writes what it would in
/// a Flutter app. A region is listed only where it differs from its language.
library;

/// By locale tag - `en`, `en_GB`, `zh_Hant_TW` - a pattern (one of `H:mm`,
/// `HH:mm`, `HH.mm`, `h:mm a`, `a h:mm`, `HH 'h' mm`), the word for the
/// morning and the word for the afternoon.
const Map<String, (String, String, String)> timeOfDayFormats = {
''');
  for (final tag in table.keys.toList()..sort()) {
    final (pattern, am, pm) = table[tag]!;
    out.writeln(
      '  ${quoted(tag)}: (${quoted(pattern)}, ${quoted(am)}, ${quoted(pm)}),',
    );
  }
  out.writeln('};');

  final file = File('packages/native_bridge/lib/src/time_formats.dart')
    ..writeAsStringSync(out.toString());
  stdout.writeln(
    '${table.length} locales (of ${stated.length} in the SDK) in ${file.path}',
  );
}

/// The SDK the `flutter` on the PATH belongs to.
String _flutterRootFromPath() {
  final which = Process.runSync('which', ['flutter']);
  final path = (which.stdout as String).trim();
  if (which.exitCode != 0 || path.isEmpty) {
    stderr.writeln('No flutter on the PATH - pass the SDK path.');
    exit(2);
  }
  // .../flutter/bin/flutter, through any symlink.
  return File(path).resolveSymbolicLinksSync().replaceFirst(
    RegExp(r'/bin/flutter$'),
    '',
  );
}
