/// Regenerates the Material Icons tables from the Flutter SDK.
///
///   dart tool/generate_material_icons.dart [path/to/flutter]
///
/// Flutter's own `Icons` class is the source of truth: it carries the
/// codepoints of the `MaterialIcons-Regular.otf` font that
/// `uses-material-design: true` bundles into every build, which is the font
/// the native renderers draw from. Taking the numbers from anywhere else would
/// be guessing at what is in that file.
///
/// Only the base names are taken. The rounded, sharp, outlined and two-tone
/// variants live in fonts Flutter does not bundle, so their codepoints would
/// draw whatever happens to sit at that number in the filled font.
library;

import 'dart:io';

void main(List<String> args) {
  final flutterRoot = args.isNotEmpty ? args.first : _flutterRootFromPath();
  final source = File(
    '$flutterRoot/packages/flutter/lib/src/material/icons.dart',
  );
  if (!source.existsSync()) {
    stderr.writeln('No icons.dart under $flutterRoot - pass the SDK path.');
    exit(2);
  }

  final pattern = RegExp(
    r"^  static const IconData (\w+) = IconData\(\s*(0x[0-9a-fA-F]+),"
    r"\s*fontFamily: 'MaterialIcons'",
    multiLine: true,
  );
  final icons = <String, String>{};
  for (final match in pattern.allMatches(source.readAsStringSync())) {
    final name = match.group(1)!;
    if (name.endsWith('_rounded') ||
        name.endsWith('_sharp') ||
        name.endsWith('_outlined') ||
        name.endsWith('_two_tone')) {
      continue;
    }
    icons[name] = match.group(2)!;
  }
  final names = icons.keys.toList()..sort();
  stdout.writeln('${names.length} icons from $flutterRoot');

  _writeCodepoints(names, icons);
  _writeIcons(names, icons);
}

String _flutterRootFromPath() {
  final flutter = Process.runSync('which', ['flutter']).stdout as String;
  final bin = File(flutter.trim()).resolveSymbolicLinksSync();
  return Directory(bin).parent.parent.path;
}

void _writeCodepoints(List<String> names, Map<String, String> icons) {
  final buffer = StringBuffer('''
/// Material Icons codepoints, so the native renderers can draw a glyph from the
/// `MaterialIcons-Regular.otf` font Flutter already bundles (via
/// `uses-material-design: true`) rather than an approximate system drawable.
///
/// The values are the codepoints from Flutter's own `Icons` class, so an icon
/// drawn here matches the one a Flutter-hosted screen would draw. The web
/// renderer keeps addressing icons by name (the Material Icons web font renders
/// the name as a ligature), so this table is additive - a builder sends both the
/// name and, when it is a known one, the codepoint.
///
/// Pure Dart on purpose: this file is reachable from the web build, which has no
/// Flutter engine, so it cannot import `package:flutter`.
///
/// GENERATED by `tool/generate_material_icons.dart`; do not edit by hand.
library;

/// Codepoint for a Material Icons [name], or null if it is not in the table.
/// A caller that needs an icon not listed here can pass its codepoint directly.
int? materialIconCodepoint(String name) => _codepoints[name];

/// How many icons the table knows, for the test that guards the generation.
int get materialIconCount => _codepoints.length;

const Map<String, int> _codepoints = {
''');
  for (final name in names) {
    buffer.writeln("  '$name': ${icons[name]},");
  }
  buffer.writeln('};');
  File(
    'packages/native_bridge/lib/src/material_icons.dart',
  ).writeAsStringSync(buffer.toString());
}

void _writeIcons(List<String> names, Map<String, String> icons) {
  final buffer = StringBuffer('''
/// The Material icons an app can name, with Flutter's own names and
/// codepoints - so `Icons.search` means the same glyph here and there.
///
/// GENERATED by `tool/generate_material_icons.dart`; do not edit by hand.
library;

import 'icon_data.dart';

abstract final class Icons {
''');
  for (final name in names) {
    final safe = _dartName(name);
    buffer.writeln(
      "  static const IconData $safe = IconData(${icons[name]}, name: '$name');",
    );
  }
  buffer.writeln('}');
  File(
    'packages/native_bridge/lib/src/icons.dart',
  ).writeAsStringSync(buffer.toString());
}

/// Flutter escapes names that collide with keywords the same way.
String _dartName(String name) =>
    const {'class', 'try', 'extension', 'switch'}.contains(name)
    ? '${name}_'
    : name;
