/// Regenerates the Material Icons tables from the Flutter SDK.
///
///   dart tool/generate_material_icons.dart [path/to/flutter]
///
/// Flutter's own `Icons` class is the source of truth: it carries the
/// codepoints of the `MaterialIcons-Regular.otf` font that
/// `uses-material-design: true` bundles into every build, which is the font
/// the native renderers draw from. Taking the numbers from anywhere else would
/// be guessing at what is in that file.
///
/// Every name is taken into `Icons`, the outlined, rounded and sharp ones
/// included: Flutter declares all of them in the one `MaterialIcons` family,
/// so they are glyphs of that same file. A declaration in any other family
/// stops the run, since no renderer here would have the font for it.
///
/// The name table (`materialIconCodepoint`) keeps the base names only. It is
/// a map looked up at run time, so unlike the `Icons` constants none of it
/// tree-shakes, and the variants would make it four times the size in every
/// web build. A variant is reached as `Icons.home_outlined.codePoint`.
///
/// The web shell gets the same font file, so a codepoint draws the same
/// picture in a browser: it is rewrapped as WOFF (each table deflated, nothing
/// altered) into `web_shell/vendor/material-icons/`, with its licence.
library;

import 'dart:io';
import 'dart:typed_data';

void main(List<String> args) {
  final flutterRoot = args.isNotEmpty ? args.first : _flutterRootFromPath();
  final source = File(
    '$flutterRoot/packages/flutter/lib/src/material/icons.dart',
  );
  if (!source.existsSync()) {
    stderr.writeln('No icons.dart under $flutterRoot - pass the SDK path.');
    exit(2);
  }

  final pattern = RegExp(
    r"^  static const IconData (\w+) = IconData\(\s*(0x[0-9a-fA-F]+),"
    r"\s*fontFamily: 'MaterialIcons'",
    multiLine: true,
  );
  final text = source.readAsStringSync();
  final icons = <String, String>{};
  for (final match in pattern.allMatches(text)) {
    icons[match.group(1)!] = match.group(2)!;
  }
  final declared = RegExp(
    r'^  static const IconData \w+ = ',
    multiLine: true,
  ).allMatches(text).length;
  if (declared != icons.length) {
    stderr.writeln(
      '$declared icons declared, ${icons.length} in MaterialIcons - '
      'the rest are in a font nothing here draws from.',
    );
    exit(2);
  }
  final names = icons.keys.toList()..sort();
  final baseNames = [
    for (final name in names)
      if (!_variant.hasMatch(name)) name,
  ];
  stdout.writeln(
    '${names.length} icons (${baseNames.length} base names) from $flutterRoot',
  );

  _writeCodepoints(baseNames, icons);
  _writeIcons(names, icons);
  _writeWebFont(flutterRoot);
}

/// The styles Flutter draws beside the filled one, by the suffix it names
/// them with.
final _variant = RegExp(r'_(outlined|rounded|sharp)$');

String _flutterRootFromPath() {
  final flutter = Process.runSync('which', ['flutter']).stdout as String;
  final bin = File(flutter.trim()).resolveSymbolicLinksSync();
  return Directory(bin).parent.parent.path;
}

void _writeCodepoints(List<String> names, Map<String, String> icons) {
  final buffer = StringBuffer('''
/// Material Icons codepoints, so the native renderers can draw a glyph from the
/// `MaterialIcons-Regular.otf` font Flutter already bundles (via
/// `uses-material-design: true`) rather than an approximate system drawable.
///
/// The values are the codepoints from Flutter's own `Icons` class, so an icon
/// drawn here matches the one a Flutter-hosted screen would draw - on the web
/// too, whose shell ships the same font. A builder that is given a name sends
/// it and, when it is a known one, the codepoint.
///
/// Base names only: the outlined, rounded and sharp variants are in `Icons`,
/// where an unused one costs nothing, and not in this map, which is kept
/// whole by any build that looks a name up.
///
/// Pure Dart on purpose: this file is reachable from the web build, which has no
/// Flutter engine, so it cannot import `package:flutter`.
///
/// GENERATED by `tool/generate_material_icons.dart`; do not edit by hand.
library;

/// Codepoint for a Material Icons [name], or null if it is not in the table.
/// A caller that needs an icon not listed here can pass its codepoint directly.
int? materialIconCodepoint(String name) => _codepoints[name];

/// How many icons the table knows, for the test that guards the generation.
int get materialIconCount => _codepoints.length;

const Map<String, int> _codepoints = {
''');
  for (final name in names) {
    buffer.writeln("  '$name': ${icons[name]},");
  }
  buffer.writeln('};');
  File(
    'packages/native_bridge/lib/src/material_icons.dart',
  ).writeAsStringSync(buffer.toString());
}

void _writeIcons(List<String> names, Map<String, String> icons) {
  final buffer = StringBuffer('''
/// The Material icons an app can name, with Flutter's own names and
/// codepoints - so `Icons.search` means the same glyph here and there. All of
/// Flutter's are here, `_outlined`, `_rounded` and `_sharp` included: they are
/// glyphs of the same font, and a constant nothing uses is not compiled in.
///
/// GENERATED by `tool/generate_material_icons.dart`; do not edit by hand.
// The names are Flutter's, underscores and all.
// ignore_for_file: constant_identifier_names
library;

import 'icon_data.dart';

abstract final class Icons {
''');
  // Flutter's names as they stand: it has already spelled the ones that
  // would not be identifiers (`class_`, `eight_k`), and `extension` is one.
  for (final name in names) {
    buffer.writeln(
      "  static const IconData $name = IconData(${icons[name]}, name: '$name');",
    );
  }
  buffer.writeln('}');
  File(
    'packages/native_bridge/lib/src/icons.dart',
  ).writeAsStringSync(buffer.toString());
}

/// Puts Flutter's icon font where the web shell serves it from, as WOFF.
///
/// WOFF is the same tables, each deflated, behind a directory that says how
/// big they were - about a third of the size on the wire, and nothing a
/// browser cannot undo exactly.
void _writeWebFont(String flutterRoot) {
  const fonts = 'bin/cache/artifacts/material_fonts';
  const vendor = 'packages/native_bridge/web_shell/vendor/material-icons';
  final otf = File('$flutterRoot/$fonts/MaterialIcons-Regular.otf');
  if (!otf.existsSync()) {
    stderr.writeln('No ${otf.path} - run `flutter precache` first.');
    exit(2);
  }
  final sfnt = otf.readAsBytesSync();
  final header = ByteData.sublistView(sfnt);
  final count = header.getUint16(4);

  // An sfnt directory entry is tag, checksum, offset, length.
  final tables = [
    for (var i = 0; i < count; i++)
      (
        tag: header.getUint32(12 + 16 * i),
        checksum: header.getUint32(16 + 16 * i),
        offset: header.getUint32(20 + 16 * i),
        length: header.getUint32(24 + 16 * i),
      ),
  ];
  int padded(int length) => (length + 3) & ~3;

  final directory = ByteData(20 * count);
  final body = BytesBuilder();
  var at = 44 + directory.lengthInBytes;
  var sfntSize = 12 + 16 * count;
  for (final (i, table) in tables.indexed) {
    final raw = Uint8List.sublistView(
      sfnt,
      table.offset,
      table.offset + table.length,
    );
    final deflated = ZLibEncoder(level: 9).convert(raw);
    // A table that does not shrink is stored as it is.
    final data = deflated.length < raw.length ? deflated : raw;
    directory
      ..setUint32(20 * i, table.tag)
      ..setUint32(20 * i + 4, at)
      ..setUint32(20 * i + 8, data.length)
      ..setUint32(20 * i + 12, table.length)
      ..setUint32(20 * i + 16, table.checksum);
    body
      ..add(data)
      ..add(Uint8List(padded(data.length) - data.length));
    at += padded(data.length);
    sfntSize += padded(table.length);
  }

  final woff = ByteData(44)
    ..setUint32(0, 0x774F4646) // 'wOFF'
    ..setUint32(4, header.getUint32(0)) // the flavour: 'OTTO', CFF outlines
    ..setUint32(8, at)
    ..setUint16(12, count)
    ..setUint32(16, sfntSize);
  final out = File('$vendor/MaterialIcons-Regular.woff')
    ..writeAsBytesSync([
      ...woff.buffer.asUint8List(),
      ...directory.buffer.asUint8List(),
      ...body.takeBytes(),
    ]);
  File(
    '$flutterRoot/$fonts/MaterialIcons_LICENSE.txt',
  ).copySync('$vendor/LICENSE');
  stdout.writeln(
    '${out.path}: ${sfnt.length} bytes of font in ${out.lengthSync()}',
  );
}
