/// DOM goldens for the web renderer.
///
/// Generated by `test/web_ui/dom_golden_test.dart`: when a golden drifts the
/// test prints the fresh markup, so an intended change is applied by pasting
/// the printed block over the constant below.
library;

/// Golden name (`<scene>__<kit>`) -> expected markup.
const Map<String, String> domGoldens = {
  'app_shell__mdl': r'''
<div class="dnn-scaffold" data-children="" data-type="Scaffold">
  <header class="dnn-appbar mdl-shadow--4dp" data-type="AppBar">
    <span class="dnn-appbar__title">
      My Todos
    </span>
  </header>
  <div class="dnn-column dnn-column--stretch" data-children="" data-type="Column">
    <div class="dnn-padding" data-children="" data-type="Padding" style="padding: 16px;">
      <div class="dnn-row" data-children="" data-type="Row" style="gap: 8px;">
        <div class="dnn-expanded" data-children="" data-type="Expanded" style="flex: 1 1 0px;">
          <div class="dnn-textfield" data-value="" data-version="" data-type="TextField">
            <label class="dnn-textfield__label" data-part="label" for="dnn-input-new_todo" hidden="">
            </label>
            <input class="dnn-textfield__input" type="text" data-part="input" id="dnn-input-new_todo" aria-label="Add a new todo..." placeholder="Add a new todo...">
            <div class="dnn-textfield__error" data-part="error" id="dnn-error-new_todo" hidden="">
            </div>
          </div>
        </div>
        <button class="mdl-button mdl-button--icon dnn-icon-button" aria-label="Add Todo" title="Add Todo" data-type="IconButton">
          <i class="material-icons">
            add
          </i>
        </button>
      </div>
    </div>
    <div class="dnn-padding" data-children="" data-type="Padding" style="padding: 8px;">
      <div class="dnn-row" data-children="" data-type="Row" style="gap: 8px;">
        <label class="dnn-checkbox" data-type="Checkbox">
          <input type="checkbox">
          <span class="dnn-checkbox__label">
          </span>
        </label>
        <div class="dnn-expanded" data-children="" data-type="Expanded" style="flex: 1 1 0px;">
          <span class="dnn-text" data-type="Text" id="todo_1_title" style="font-size: 16px; color: rgb(158, 158, 158); text-decoration: line-through;">
            Buy milk
          </span>
        </div>
      </div>
    </div>
    <span class="dnn-text" data-type="Text" id="todo_summary" style="color: rgb(117, 117, 117);">
      1 of 1 completed
    </span>
  </div>
  <button class="mdl-button mdl-button--fab mdl-button--colored dnn-fab" aria-label="Add" title="Add" data-type="FloatingActionButton">
    <i class="material-icons">
      add
    </i>
  </button>
</div>
''',

  'app_shell__materialize': r'''
<div class="dnn-scaffold" data-children="" data-type="Scaffold">
  <nav class="dnn-appbar dnn-mz-nav blue darken-2" data-type="AppBar">
    <div class="nav-wrapper">
      <span class="dnn-mz-nav__title">
        My Todos
      </span>
    </div>
  </nav>
  <div class="dnn-column dnn-column--stretch" data-children="" data-type="Column">
    <div class="dnn-padding" data-children="" data-type="Padding" style="padding: 16px;">
      <div class="dnn-row" data-children="" data-type="Row" style="gap: 8px;">
        <div class="dnn-expanded" data-children="" data-type="Expanded" style="flex: 1 1 0px;">
          <div class="input-field dnn-mz-textfield" data-value="" data-version="" data-type="TextField">
            <input class="" type="text" data-part="input" id="dnn-input-new_todo" aria-label="Add a new todo..." placeholder="Add a new todo...">
            <label class="active" data-part="label" for="dnn-input-new_todo" hidden="">
            </label>
            <span class="helper-text dnn-mz-textfield__error" data-part="error" id="dnn-error-new_todo" hidden="">
            </span>
          </div>
        </div>
        <button class="btn-flat dnn-mz-icon-button" aria-label="Add Todo" title="Add Todo" data-type="IconButton">
          <i class="material-icons">
            add
          </i>
        </button>
      </div>
    </div>
    <div class="dnn-padding" data-children="" data-type="Padding" style="padding: 8px;">
      <div class="dnn-row" data-children="" data-type="Row" style="gap: 8px;">
        <label class="dnn-mz-choice" data-type="Checkbox">
          <input type="checkbox" class="filled-in">
          <span class="">
          </span>
        </label>
        <div class="dnn-expanded" data-children="" data-type="Expanded" style="flex: 1 1 0px;">
          <span class="dnn-text" data-type="Text" id="todo_1_title" style="font-size: 16px; color: rgb(158, 158, 158); text-decoration: line-through;">
            Buy milk
          </span>
        </div>
      </div>
    </div>
    <span class="dnn-text" data-type="Text" id="todo_summary" style="color: rgb(117, 117, 117);">
      1 of 1 completed
    </span>
  </div>
  <button class="btn-floating btn-large blue darken-2 dnn-fab" aria-label="Add" title="Add" data-type="FloatingActionButton">
    <i class="material-icons">
      add
    </i>
  </button>
</div>
''',

  'app_shell__plain': r'''
<div class="dnn-scaffold" data-children="" data-type="Scaffold">
  <header class="dnn-appbar" data-type="AppBar">
    <span class="dnn-appbar__title">
      My Todos
    </span>
  </header>
  <div class="dnn-column dnn-column--stretch" data-children="" data-type="Column">
    <div class="dnn-padding" data-children="" data-type="Padding" style="padding: 16px;">
      <div class="dnn-row" data-children="" data-type="Row" style="gap: 8px;">
        <div class="dnn-expanded" data-children="" data-type="Expanded" style="flex: 1 1 0px;">
          <div class="dnn-textfield" data-value="" data-version="" data-type="TextField">
            <label class="dnn-textfield__label" data-part="label" for="dnn-input-new_todo" hidden="">
            </label>
            <input class="dnn-textfield__input" type="text" data-part="input" id="dnn-input-new_todo" aria-label="Add a new todo..." placeholder="Add a new todo...">
            <div class="dnn-textfield__error" data-part="error" id="dnn-error-new_todo" hidden="">
            </div>
          </div>
        </div>
        <button class="dnn-icon-button" aria-label="Add Todo" title="Add Todo" data-type="IconButton">
          <i class="material-icons">
            add
          </i>
        </button>
      </div>
    </div>
    <div class="dnn-padding" data-children="" data-type="Padding" style="padding: 8px;">
      <div class="dnn-row" data-children="" data-type="Row" style="gap: 8px;">
        <label class="dnn-checkbox" data-type="Checkbox">
          <input type="checkbox">
          <span class="dnn-checkbox__label">
          </span>
        </label>
        <div class="dnn-expanded" data-children="" data-type="Expanded" style="flex: 1 1 0px;">
          <span class="dnn-text" data-type="Text" id="todo_1_title" style="font-size: 16px; color: rgb(158, 158, 158); text-decoration: line-through;">
            Buy milk
          </span>
        </div>
      </div>
    </div>
    <span class="dnn-text" data-type="Text" id="todo_summary" style="color: rgb(117, 117, 117);">
      1 of 1 completed
    </span>
  </div>
  <button class="dnn-fab dnn-fab--plain" aria-label="Add" title="Add" data-type="FloatingActionButton">
    <i class="material-icons">
      add
    </i>
  </button>
</div>
''',

  'components__mdl': r'''
<div class="dnn-column dnn-column--stretch" data-children="" data-type="Column">
  <button class="mdl-button mdl-button--raised dnn-mdl-button dnn-mdl-button--primary dnn-mdl-button--md" data-type="Button">
    Primary
  </button>
  <button class="mdl-button mdl-button--raised dnn-mdl-button dnn-mdl-button--secondary dnn-mdl-button--md" data-type="Button">
    Secondary
  </button>
  <button class="mdl-button mdl-button--raised dnn-mdl-button dnn-mdl-button--primary dnn-mdl-button--md" disabled="" data-type="Button">
    Disabled
  </button>
  <div class="mdl-card dnn-mdl-card dnn-mdl-card--elevated mdl-shadow--4dp" data-type="Card">
    <div class="mdl-card__title">
      <h2 class="mdl-card__title-text">
        Card
      </h2>
    </div>
    <div class="mdl-card__supporting-text dnn-mdl-card__content" data-children="" style="padding: 16px;">
      <span class="dnn-text" data-type="Text">
        Card body
      </span>
    </div>
  </div>
  <span class="mdl-chip dnn-mdl-chip dnn-mdl-chip--solid" data-type="Badge" style="background: rgb(25, 118, 210); color: rgb(255, 255, 255);">
    <span class="mdl-chip__text">
      New
    </span>
  </span>
  <img class="dnn-image" src="vendor/roboto/roboto.css" alt="A placeholder image" data-type="Image" style="width: 64px; height: 64px; object-fit: cover;">
  <div class="dnn-alert dnn-alert--info" role="alert" data-type="Alert">
    <div class="dnn-alert__body">
      <span class="dnn-alert__title">
        Info
      </span>
      <span class="dnn-alert__message">
        Heads up
      </span>
    </div>
    <button class="dnn-alert__close" aria-label="Dismiss">
      ×
    </button>
  </div>
  <label class="dnn-checkbox" data-type="Checkbox">
    <input type="checkbox">
    <span class="dnn-checkbox__label">
      Checked
    </span>
  </label>
  <label class="dnn-radio" data-type="Radio">
    <input type="radio">
    <span class="dnn-radio__label">
      Radio
    </span>
  </label>
  <label class="dnn-switch" data-type="Toggle">
    <input type="checkbox" role="switch">
    <span class="dnn-switch__track">
    </span>
    <span class="dnn-switch__label">
      Toggle
    </span>
  </label>
  <div class="dnn-divider" data-type="Divider" style="height: 1px; margin: 16px 0px;">
  </div>
  <div class="dnn-progress" data-type="Loading" style="color: rgb(25, 118, 210);">
    <div class="dnn-progress__bar" style="width: 50%;">
    </div>
  </div>
  <div class="mdl-list dnn-mdl-list" data-children="" data-type="ListView">
    <div class="mdl-list__item mdl-list__item--two-line" data-type="ListItem">
      <span class="mdl-list__item-primary-content">
        <span class="dnn-mdl-list__text">
          Item
        </span>
        <span class="mdl-list__item-sub-title">
          Subtitle
        </span>
      </span>
    </div>
  </div>
  <div class="dnn-textfield dnn-textfield--floating dnn-textfield--error" data-value="" data-version="" data-type="TextField">
    <label class="dnn-textfield__label" data-part="label" for="dnn-input-email">
      Email
    </label>
    <input class="dnn-textfield__input" type="text" data-part="input" id="dnn-input-email" placeholder="you@example.com" aria-invalid="true" aria-describedby="dnn-error-email">
    <div class="dnn-textfield__error" data-part="error" id="dnn-error-email">
      Invalid email
    </div>
  </div>
</div>
''',

  'components__materialize': r'''
<div class="dnn-column dnn-column--stretch" data-children="" data-type="Column">
  <button class="btn blue darken-2 dnn-mz-button" data-type="Button">
    Primary
  </button>
  <button class="btn orange darken-2 dnn-mz-button" data-type="Button">
    Secondary
  </button>
  <button class="btn blue darken-2 dnn-mz-button" disabled="" data-type="Button">
    Disabled
  </button>
  <div class="card dnn-mz-card dnn-mz-card--elevated z-depth-1" data-type="Card">
    <div class="card-content" style="padding: 16px;">
      <span class="card-title">
        Card
      </span>
      <div class="dnn-mz-card__body" data-children="">
        <span class="dnn-text" data-type="Text">
          Card body
        </span>
      </div>
    </div>
  </div>
  <span class="chip dnn-mz-chip dnn-mz-chip--solid" data-type="Badge" style="background: rgb(25, 118, 210); color: rgb(255, 255, 255);">
    New
  </span>
  <img class="dnn-image" src="vendor/roboto/roboto.css" alt="A placeholder image" data-type="Image" style="width: 64px; height: 64px; object-fit: cover;">
  <div class="card-panel dnn-mz-alert light-blue lighten-5 light-blue-text text-darken-4" role="alert" data-type="Alert">
    <div class="dnn-mz-alert__body">
      <strong class="dnn-mz-alert__title">
        Info
      </strong>
      <span class="dnn-mz-alert__message">
        Heads up
      </span>
    </div>
    <button class="btn-flat dnn-mz-alert__close" aria-label="Dismiss">
      <i class="material-icons">
        close
      </i>
    </button>
  </div>
  <label class="dnn-mz-choice" data-type="Checkbox">
    <input type="checkbox" class="filled-in">
    <span class="">
      Checked
    </span>
  </label>
  <label class="dnn-mz-choice" data-type="Radio">
    <input type="radio" class="with-gap">
    <span class="">
      Radio
    </span>
  </label>
  <div class="switch dnn-mz-switch" data-type="Toggle">
    <label class="">
      <input type="checkbox">
      <span class="lever">
      </span>
      <span class="dnn-mz-switch__label">
        Toggle
      </span>
    </label>
  </div>
  <div class="dnn-divider" data-type="Divider" style="height: 1px; margin: 16px 0px;">
  </div>
  <div class="progress dnn-mz-progress" data-type="Loading">
    <div class="determinate" style="width: 50%; background-color: rgb(25, 118, 210);">
    </div>
  </div>
  <div class="collection dnn-mz-list" data-children="" data-type="ListView">
    <div class="collection-item" data-type="ListItem">
      <span class="title">
        Item
      </span>
      <p class="dnn-mz-list__subtitle">
        Subtitle
      </p>
    </div>
  </div>
  <div class="input-field dnn-mz-textfield dnn-textfield--floating" data-value="" data-version="" data-type="TextField">
    <input class="invalid" type="text" data-part="input" id="dnn-input-email" placeholder="you@example.com" aria-invalid="true" aria-describedby="dnn-error-email">
    <label class="active" data-part="label" for="dnn-input-email">
      Email
    </label>
    <span class="helper-text dnn-mz-textfield__error" data-part="error" id="dnn-error-email">
      Invalid email
    </span>
  </div>
</div>
''',

  'components__plain': r'''
<div class="dnn-column dnn-column--stretch" data-children="" data-type="Column">
  <button class="dnn-button dnn-button--primary dnn-button--md" data-type="Button">
    Primary
  </button>
  <button class="dnn-button dnn-button--secondary dnn-button--md" data-type="Button">
    Secondary
  </button>
  <button class="dnn-button dnn-button--primary dnn-button--md" disabled="" data-type="Button">
    Disabled
  </button>
  <div class="dnn-card dnn-card--elevated" data-type="Card" style="box-shadow: rgba(0, 0, 0, 0.14) 0px 2px 4px, rgba(0, 0, 0, 0.12) 0px 1px 2px;">
    <div class="dnn-card__title">
      Card
    </div>
    <div class="dnn-card__content" data-children="" style="padding: 16px;">
      <span class="dnn-text" data-type="Text">
        Card body
      </span>
    </div>
  </div>
  <span class="dnn-badge dnn-badge--solid" data-type="Badge" style="background: rgb(25, 118, 210); color: rgb(255, 255, 255);">
    New
  </span>
  <img class="dnn-image" src="vendor/roboto/roboto.css" alt="A placeholder image" data-type="Image" style="width: 64px; height: 64px; object-fit: cover;">
  <div class="dnn-alert dnn-alert--info" role="alert" data-type="Alert">
    <div class="dnn-alert__body">
      <span class="dnn-alert__title">
        Info
      </span>
      <span class="dnn-alert__message">
        Heads up
      </span>
    </div>
    <button class="dnn-alert__close" aria-label="Dismiss">
      ×
    </button>
  </div>
  <label class="dnn-checkbox" data-type="Checkbox">
    <input type="checkbox">
    <span class="dnn-checkbox__label">
      Checked
    </span>
  </label>
  <label class="dnn-radio" data-type="Radio">
    <input type="radio">
    <span class="dnn-radio__label">
      Radio
    </span>
  </label>
  <label class="dnn-switch" data-type="Toggle">
    <input type="checkbox" role="switch">
    <span class="dnn-switch__track">
    </span>
    <span class="dnn-switch__label">
      Toggle
    </span>
  </label>
  <div class="dnn-divider" data-type="Divider" style="height: 1px; margin: 16px 0px;">
  </div>
  <div class="dnn-progress" data-type="Loading" style="color: rgb(25, 118, 210);">
    <div class="dnn-progress__bar" style="width: 50%;">
    </div>
  </div>
  <div class="dnn-list" data-children="" data-type="ListView">
    <div class="dnn-list-item" data-type="ListItem">
      <span class="dnn-list-item__text">
        Item
      </span>
      <span class="dnn-list-item__subtitle">
        Subtitle
      </span>
    </div>
  </div>
  <div class="dnn-textfield dnn-textfield--floating dnn-textfield--error" data-value="" data-version="" data-type="TextField">
    <label class="dnn-textfield__label" data-part="label" for="dnn-input-email">
      Email
    </label>
    <input class="dnn-textfield__input" type="text" data-part="input" id="dnn-input-email" placeholder="you@example.com" aria-invalid="true" aria-describedby="dnn-error-email">
    <div class="dnn-textfield__error" data-part="error" id="dnn-error-email">
      Invalid email
    </div>
  </div>
</div>
''',
};
